/**
 * Oxocarbon Dark Theme for CodeMirror 6
 *
 * Based on IBM's Carbon Design System color palette.
 * A deep, accessible dark theme with vibrant accent colors.
 *
 * @see https://carbondesignsystem.com/guidelines/color/overview/
 */

import { HighlightStyle, syntaxHighlighting } from "@codemirror/language";
import { EditorView } from "@codemirror/view";
import { tags } from "@lezer/highlight";

const colors = {
  background: "#161616",
  surface: "#262626",
  text: "#f2f4f8",
  textMuted: "#dde1e6",
  textDisabled: "#525252",
  border: "#393939",
  blue: "#33b1ff",
  cyan: "#3ddbd9",
  green: "#42be65",
  magenta: "#ee5396",
  orange: "#ff6f00",
  purple: "#be95ff",
  red: "#ff7eb6",
  teal: "#08bdba",
  yellow: "#ff6f00",
  white: "#ffffff",
  black: "#000000",
};

export const oxocarbonDarkTheme = EditorView.theme({
  "&": {
    backgroundColor: colors.background,
    color: colors.text,
    fontSize: "14px",
    fontFamily: "\"IBM Plex Mono\", \"SF Mono\", Monaco, monospace",
  },
  ".cm-content": { caretColor: colors.cyan, padding: "16px 0" },
  ".cm-cursor": { borderLeftColor: colors.cyan, borderLeftWidth: "2px" },
  "&.cm-focused .cm-cursor": { borderLeftColor: colors.cyan },
  "&.cm-focused .cm-selectionBackground": { backgroundColor: "rgba(51, 177, 255, 0.3)" },
  ".cm-selectionBackground": { backgroundColor: "rgba(51, 177, 255, 0.2)" },
  ".cm-activeLine": { backgroundColor: "rgba(57, 57, 57, 0.5)" },
  ".cm-activeLineGutter": { backgroundColor: colors.surface },
  ".cm-gutters": {
    backgroundColor: colors.background,
    color: colors.textMuted,
    borderRight: `1px solid ${colors.border}`,
    paddingRight: "8px",
  },
  ".cm-lineNumbers .cm-gutterElement": { padding: "0 8px", minWidth: "32px" },
  ".cm-foldPlaceholder": {
    backgroundColor: colors.surface,
    border: `1px solid ${colors.border}`,
    borderRadius: "3px",
    color: colors.textMuted,
    padding: "0 4px",
  },
  ".cm-foldGutter .cm-gutterElement": { color: colors.textMuted, cursor: "pointer" },
  ".cm-tooltip": {
    backgroundColor: colors.surface,
    border: `1px solid ${colors.border}`,
    borderRadius: "4px",
    boxShadow: "0 4px 12px rgba(0, 0, 0, 0.5)",
  },
  ".cm-tooltip-autocomplete": { backgroundColor: colors.surface },
  ".cm-tooltip-autocomplete ul li[aria-selected]": { backgroundColor: colors.blue, color: colors.white },
  ".cm-completionLabel": { color: colors.text },
  ".cm-completionDetail": { color: colors.textMuted },
  ".cm-completionIcon": { color: colors.cyan },
  ".cm-searchMatch": { backgroundColor: "rgba(255, 111, 0, 0.3)", outline: `1px solid ${colors.yellow}` },
  ".cm-searchMatch.cm-searchMatch-selected": { backgroundColor: "rgba(255, 111, 0, 0.5)" },
  ".cm-panel": { backgroundColor: colors.surface, borderTop: `1px solid ${colors.border}` },
  ".cm-panel button": {
    backgroundColor: colors.blue,
    color: colors.white,
    border: "none",
    borderRadius: "3px",
    padding: "4px 12px",
    cursor: "pointer",
  },
  ".cm-panel input": {
    backgroundColor: colors.background,
    color: colors.text,
    border: `1px solid ${colors.border}`,
    borderRadius: "3px",
    padding: "4px 8px",
  },
  ".cm-placeholder": { color: colors.textMuted },
  ".cm-highlight": { backgroundColor: "rgba(255, 111, 0, 0.3)" },
  ".cm-specialChar": { color: colors.red },
  "& .cm-scroller::-webkit-scrollbar": { width: "10px", height: "10px" },
  "& .cm-scroller::-webkit-scrollbar-track": { background: colors.background },
  "& .cm-scroller::-webkit-scrollbar-thumb": { background: colors.border, borderRadius: "5px" },
  "& .cm-scroller::-webkit-scrollbar-thumb:hover": { background: colors.textDisabled },
  "& .cm-scroller": { scrollbarColor: `${colors.border} ${colors.background}`, scrollbarWidth: "thin" },
}, { dark: true });

export const oxocarbonDarkHighlight = HighlightStyle.define([
  { tag: tags.keyword, color: colors.magenta, fontWeight: "bold" },
  { tag: tags.controlKeyword, color: colors.magenta },
  { tag: tags.definitionKeyword, color: colors.magenta },
  { tag: tags.modifier, color: colors.magenta },
  { tag: tags.operatorKeyword, color: colors.magenta },
  { tag: tags.function(tags.variableName), color: colors.blue },
  { tag: tags.function(tags.definition(tags.variableName)), color: colors.blue },
  { tag: tags.labelName, color: colors.cyan },
  { tag: tags.namespace, color: colors.cyan },
  { tag: tags.macroName, color: colors.cyan },
  { tag: tags.literal, color: colors.teal },
  { tag: tags.string, color: colors.green },
  { tag: tags.docString, color: colors.green },
  { tag: tags.character, color: colors.green },
  { tag: tags.attributeValue, color: colors.green },
  { tag: tags.number, color: colors.teal },
  { tag: tags.integer, color: colors.teal },
  { tag: tags.float, color: colors.teal },
  { tag: tags.bool, color: colors.teal },
  { tag: tags.regexp, color: colors.orange },
  { tag: tags.escape, color: colors.orange },
  { tag: tags.color, color: colors.orange },
  { tag: tags.url, color: colors.cyan, textDecoration: "underline" },
  { tag: tags.keyword, color: colors.magenta },
  { tag: tags.self, color: colors.purple },
  { tag: tags.null, color: colors.purple },
  { tag: tags.atom, color: colors.purple },
  { tag: tags.unit, color: colors.purple },
  { tag: tags.modifier, color: colors.magenta },
  { tag: tags.operator, color: colors.cyan },
  { tag: tags.derefOperator, color: colors.cyan },
  { tag: tags.arithmeticOperator, color: colors.cyan },
  { tag: tags.logicOperator, color: colors.cyan },
  { tag: tags.bitwiseOperator, color: colors.cyan },
  { tag: tags.compareOperator, color: colors.cyan },
  { tag: tags.updateOperator, color: colors.cyan },
  { tag: tags.definitionOperator, color: colors.cyan },
  { tag: tags.typeOperator, color: colors.magenta },
  { tag: tags.controlOperator, color: colors.cyan },
  { tag: tags.punctuation, color: colors.text },
  { tag: tags.separator, color: colors.text },
  { tag: tags.bracket, color: colors.text },
  { tag: tags.angleBracket, color: colors.text },
  { tag: tags.squareBracket, color: colors.text },
  { tag: tags.paren, color: colors.text },
  { tag: tags.brace, color: colors.text },
  { tag: tags.contentSeparator, color: colors.text },
  { tag: tags.comment, color: colors.textMuted, fontStyle: "italic" },
  { tag: tags.lineComment, color: colors.textMuted, fontStyle: "italic" },
  { tag: tags.blockComment, color: colors.textMuted, fontStyle: "italic" },
  { tag: tags.docComment, color: colors.textMuted, fontStyle: "italic" },
  { tag: tags.name, color: colors.text },
  { tag: tags.variableName, color: colors.text },
  { tag: tags.typeName, color: colors.yellow },
  { tag: tags.tagName, color: colors.blue },
  { tag: tags.attributeName, color: colors.cyan },
  { tag: tags.className, color: colors.yellow },
  { tag: tags.labelName, color: colors.cyan },
  { tag: tags.namespace, color: colors.cyan },
  { tag: tags.macroName, color: colors.cyan },
  { tag: tags.propertyName, color: colors.cyan },
  { tag: tags.special(tags.propertyName), color: colors.cyan },
  { tag: tags.heading1, color: colors.blue, fontWeight: "bold", fontSize: "1.5em" },
  { tag: tags.heading2, color: colors.blue, fontWeight: "bold", fontSize: "1.3em" },
  { tag: tags.heading3, color: colors.blue, fontWeight: "bold", fontSize: "1.1em" },
  { tag: tags.heading4, color: colors.blue, fontWeight: "bold" },
  { tag: tags.heading5, color: colors.blue, fontWeight: "bold" },
  { tag: tags.heading6, color: colors.blue, fontWeight: "bold" },
  { tag: tags.heading, color: colors.blue, fontWeight: "bold" },
  { tag: tags.quote, color: colors.green, fontStyle: "italic" },
  { tag: tags.list, color: colors.cyan },
  { tag: tags.emphasis, color: colors.text, fontStyle: "italic" },
  { tag: tags.strong, color: colors.text, fontWeight: "bold" },
  { tag: tags.strikethrough, color: colors.textMuted, textDecoration: "line-through" },
  { tag: tags.link, color: colors.cyan, textDecoration: "underline" },
  { tag: tags.monospace, color: colors.orange, fontFamily: "monospace" },
  { tag: tags.processingInstruction, color: colors.magenta },
  { tag: tags.annotation, color: colors.yellow },
  { tag: tags.invalid, color: colors.red, borderBottom: `1px dotted ${colors.red}` },
  { tag: tags.meta, color: colors.textMuted },
  { tag: tags.documentMeta, color: colors.textMuted },

  { tag: tags.changed, color: colors.yellow },
  { tag: tags.deleted, color: colors.red },
  { tag: tags.inserted, color: colors.green },
]);

export const oxocarbonDark = [oxocarbonDarkTheme, syntaxHighlighting(oxocarbonDarkHighlight)];
